### ISSUE TITLE
'NoneType' object is not callable error with superset = 0.29.0rc7 

### ISSUE THREAD

**Issue by Towhid1** [Kyligence/kylinpy#20]
2019-04-04 09:25:34,763:ERROR:root:'NoneType' object is not callable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/sql_lab.py", line 183, in execute_sql
    db_engine_spec.execute(cursor, query.executed_sql, async_=True)
  File "/usr/local/lib/python3.6/site-packages/superset/db_engine_specs.py", line 375, in execute
    cursor.execute(query)
  File "/home/superset/.local/lib/python3.6/site-packages/kylinpy/kylindb.py", line 48, in execute
    ] for row in resp['results']]
  File "/home/superset/.local/lib/python3.6/site-packages/kylinpy/kylindb.py", line 48, in <listcomp>
    ] for row in resp['results']]
  File "/home/superset/.local/lib/python3.6/site-packages/kylinpy/kylindb.py", line 47, in <listcomp>
    for (col, cell) in enumerate(row)
  File "/home/superset/.local/lib/python3.6/site-packages/kylinpy/utils/kylin_types.py", line 39, in kylin_to_python
    return KylinType.get(str(_type).upper())(s) if s else s
TypeError: 'NoneType' object is not callable

**Comment by zhaoyongjie** [comment]
@Towhid1 , Thank you for you feedback, and your pull review. I made some change to the code based on your clues. you can download newest Kylinpy 2.3.1, fix this issue.

```
pip install -U kylinpy
```
